"""Add due_date to todos table

Revision ID: 8a02a02a6a5d
Revises: 4c0d65a0799b
Create Date: 2025-12-17 01:26:03.573437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a02a02a6a5d'
down_revision: Union[str, None] = '4c0d65a0799b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'due_date')
    # ### end Alembic commands ###
